apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: project-production
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: 297a9e854424d41ec4732548f06bb75555a0d85b
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: 297a9e854424d41ec4732548f06bb75555a0d85b
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: 297a9e854424d41ec4732548f06bb75555a0d85b
