apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
  namespace: exercises
  labels:
    app: greeter
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: greeter
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-1
  namespace: exercises
  labels:
    app: greeter
    version: v1
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: greeter
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-2
  namespace: exercises
  labels:
    app: greeter
    version: v2
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: greeter
    version: v2
