apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- gateway.yaml
- pvc.yaml
- route.yaml
- service.yaml
images:
- name: log-reader/image
  newName: aljazkovac/log-reader
  newTag: f067849221483a7da78d670ecf0cdcd0949a9d72
- name: log-writer/image
  newName: aljazkovac/log-writer
  newTag: f067849221483a7da78d670ecf0cdcd0949a9d72
