apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-app-configmap.yaml
  - todo-app-deployment.yaml
  - todo-app-pvc.yaml
  - todo-app-svc.yaml
  - todo-backend-configmap.yaml
  - todo-backend-deployment.yaml
  - todo-backend-postgres-svc.yaml
  - todo-backend-statefulset.yaml
  - todo-backend-svc.yaml
  - todo-backend-todo-cronjob.yaml
  - todo-backend-dbdump-cronjob.yaml
  - todo-project-gateway.yaml
  - todo-project-route.yaml
  - todo-project-quota.yaml
  - todo-project-limitrange.yaml
  - todo-broadcaster-deployment.yaml
