apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app/image
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: port
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: todo_backend_url
            - name: IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: image_dir
            - name: CURRENT_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: current_image_name
            - name: METADATA_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: metadata_name
            - name: CACHE_DURATION_MS
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: cache_duration_ms
            - name: PICSUM_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-configmap
                  key: picsum_url
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: todo-app-storage
              mountPath: /app/images
      volumes:
        - name: todo-app-storage
          persistentVolumeClaim:
            claimName: todo-app-pvc
