apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster-deployment
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: todo-broadcaster/image
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-configmap
                  key: NATS_URL
            - name: WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-backend-configmap
                  key: WEBHOOK_URL
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
