apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-configmap
data:
  PORT: "3001"
  SERVICE_NAME: "todo-backend-svc"
  POSTGRES_HOST: "todo-backend-postgres-svc"
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword
  NATS_URL: "nats://my-nats.project.svc.cluster.local:4222"
  WEBHOOK_URL: "https://study.cs.helsinki.fi/discord/webhooks/1264842173619109949"
