apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging

patches:
  - target:
      kind: CronJob
      name: todo-backend-db-backup-cronjob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: todo-backend-db-backup-cronjob
      spec:
        suspend: true
  - target:
      kind: ConfigMap
      name: todo-backend-configmap
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: todo-backend-configmap
      data:
        WEBHOOK_URL: ""
