apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: project-staging

patches:
- patch: |-
    apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: todo-backend-db-backup-cronjob
    spec:
      suspend: true
  target:
    kind: CronJob
    name: todo-backend-db-backup-cronjob
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: todo-backend-configmap
    data:
      WEBHOOK_URL: ""
  target:
    kind: ConfigMap
    name: todo-backend-configmap
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
