apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy-site-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummy-site-controller-role
rules:
  # Permissions for our custom resource
  - apiGroups: ["stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "update", "patch"]
  # Permissions to manage standard resources created by the controller
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummy-site-controller-binding
subjects:
  - kind: ServiceAccount
    name: dummy-site-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dummy-site-controller-role
  apiGroup: rbac.authorization.k8s.io
