apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-development
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: 38408ebcd3fe6d51c141b58e3cbb3b9d86bf26ab
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: 38408ebcd3fe6d51c141b58e3cbb3b9d86bf26ab
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: 38408ebcd3fe6d51c141b58e3cbb3b9d86bf26ab
