apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: 9e5a7f74796006d62e9a74a52108c53f2033e067
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: 9e5a7f74796006d62e9a74a52108c53f2033e067
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: 9e5a7f74796006d62e9a74a52108c53f2033e067
