apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-development
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: b928b04be7c9b34d1f044d897e73d4f0c6b94499
