apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: cacfd3b9e3656ba96a4c5b504bd5cc6640fdbda7
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: cacfd3b9e3656ba96a4c5b504bd5cc6640fdbda7
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: cacfd3b9e3656ba96a4c5b504bd5cc6640fdbda7
