apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-development
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: 47a3900c2193d165c572329f2ab235e7635d7413
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: 47a3900c2193d165c572329f2ab235e7635d7413
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: 47a3900c2193d165c572329f2ab235e7635d7413
