apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: todo-app/image
  newName: aljazkovac/todo-app
  newTag: 18849f93f555ad3a57c52104d37bf171d331f6f5
- name: todo-backend/image
  newName: aljazkovac/todo-backend
  newTag: 18849f93f555ad3a57c52104d37bf171d331f6f5
- name: todo-broadcaster/image
  newName: aljazkovac/todo-broadcaster
  newTag: 18849f93f555ad3a57c52104d37bf171d331f6f5
