name: Build and publish Todo Project application

on:
  push:
    paths:
      - "todo-project/**"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish TODO app image
        working-directory: todo-project/todo-app
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-app:$GITHUB_SHA" . --push

      - name: Build and publish TODO backend image
        working-directory: todo-project/todo-backend
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-backend:$GITHUB_SHA" . --push

      - name: Build and publish TODO broadcaster image
        working-directory: todo-project/broadcaster
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-broadcaster:$GITHUB_SHA" . --push

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image for TODO app
        working-directory: todo-project/kustomize/overlays/development
        run: kustomize edit set image todo-app/image=aljazkovac/todo-app:$GITHUB_SHA

      - name: Use right image for TODO backend
        working-directory: todo-project/kustomize/overlays/development
        run: kustomize edit set image todo-backend/image=aljazkovac/todo-backend:$GITHUB_SHA

      - name: Use right image for TODO broadcaster
        working-directory: todo-project/kustomize/overlays/development
        run: kustomize edit set image todo-broadcaster/image=aljazkovac/todo-broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "todo-project/kustomize/overlays/development/kustomization.yaml"
          message: New version released ${{ github.sha }}
