name: Build and publish Todo Project (Production)

on:
  push:
    tags:
      - "todo-v*"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Tag (Code Repo)
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish TODO app image
        working-directory: todo-project/todo-app
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-app:$GITHUB_SHA" . --push

      - name: Build and publish TODO backend image
        working-directory: todo-project/todo-backend
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-backend:$GITHUB_SHA" . --push

      - name: Build and publish TODO broadcaster image
        working-directory: todo-project/broadcaster
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-broadcaster:$GITHUB_SHA" . --push

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      # ==========================================
      # CHECKOUT CONFIG REPO
      # ==========================================
      - name: Checkout Config Repo
        uses: actions/checkout@v4
        with:
          repository: aljazkovac/devops-with-kubernetes-gitops
          path: config-repo
          token: ${{ secrets.CONFIG_REPO_PAT }}

      # ==========================================
      # PRODUCTION DEPLOYMENT
      # ==========================================
      - name: Update Production Image Tags
        working-directory: config-repo/todo-project/kustomize/overlays/production
        run: |
          kustomize edit set image todo-app/image=aljazkovac/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend/image=aljazkovac/todo-backend:$GITHUB_SHA
          kustomize edit set image todo-broadcaster/image=aljazkovac/todo-broadcaster:$GITHUB_SHA

            # ==========================================

            # COMMIT CHANGES TO CONFIG REPO

            # ==========================================

            - name: Commit and Push to Config Repo

              uses: EndBug/add-and-commit@v9

              with:

                cwd: './config-repo'

                add: '.'

                message: "Update images to ${{ github.sha }} (Production: ${{ github.ref_name }})"

      