name: Build and publish Todo Project application

on:
  push:
    paths:
      - "todo-project/**"
    tags:
      - "v*"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish TODO app image
        working-directory: todo-project/todo-app
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-app:$GITHUB_SHA" . --push

      - name: Build and publish TODO backend image
        working-directory: todo-project/todo-backend
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-backend:$GITHUB_SHA" . --push

      - name: Build and publish TODO broadcaster image
        working-directory: todo-project/broadcaster
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/todo-broadcaster:$GITHUB_SHA" . --push

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      # ==========================================
      # DEVELOPMENT DEPLOYMENT (Main Branch)
      # ==========================================
      - name: Update Development Image Tags
        if: github.ref == 'refs/heads/main'
        working-directory: todo-project/kustomize/overlays/development
        run: |
          kustomize edit set image todo-app/image=aljazkovac/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend/image=aljazkovac/todo-backend:$GITHUB_SHA
          kustomize edit set image todo-broadcaster/image=aljazkovac/todo-broadcaster:$GITHUB_SHA

      # ==========================================
      # STAGING DEPLOYMENT (Main Branch)
      # ==========================================
      - name: Update Staging Image Tags
        if: github.ref == 'refs/heads/main'
        working-directory: todo-project/kustomize/overlays/staging
        run: |
          kustomize edit set image todo-app/image=aljazkovac/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend/image=aljazkovac/todo-backend:$GITHUB_SHA
          kustomize edit set image todo-broadcaster/image=aljazkovac/todo-broadcaster:$GITHUB_SHA

      # ==========================================
      # COMMIT DEVELOPMENT AND STAGING CHANGES (Main Branch)
      # ==========================================

      - name: Commit Development And Staging Kustomization
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            todo-project/kustomize/overlays/development/kustomization.yaml
            todo-project/kustomize/overlays/staging/kustomization.yaml
          message: "Development and Staging deployment: ${{ github.sha }}"

      # ==========================================
      # PRODUCTION DEPLOYMENT (Tags)
      # ==========================================
      - name: Update Production Image Tags
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: todo-project/kustomize/overlays/production
        run: |
          kustomize edit set image todo-app/image=aljazkovac/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend/image=aljazkovac/todo-backend:$GITHUB_SHA
          kustomize edit set image todo-broadcaster/image=aljazkovac/todo-broadcaster:$GITHUB_SHA

      - name: Commit Production Kustomization
        if: startsWith(github.ref, 'refs/tags/')
        uses: EndBug/add-and-commit@v9
        with:
          add: todo-project/kustomize/overlays/production/kustomization.yaml
          message: "Production deployment: ${{ github.ref_name }}"
