name: Build and publish application

on:
  push:
    paths:
      - "log-output/**"

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish log-reader image
        working-directory: log-output/log-reader
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/log-reader:$GITHUB_SHA" . --push

      - name: Build and publish log-writer image
        working-directory: log-output/log-writer
        run: |-
          docker buildx build --platform linux/amd64 -t "aljazkovac/log-writer:$GITHUB_SHA" . --push

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image for log-reader
        working-directory: log-output/kustomize/base
        run: kustomize edit set image log-reader/image=aljazkovac/log-reader:$GITHUB_SHA

      - name: Use right image for log-writer
        working-directory: log-output/kustomize/base
        run: kustomize edit set image log-writer/image=aljazkovac/log-writer:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "log-output/kustomize/base/kustomization.yaml"
          message: New version released ${{ github.sha }}
