name: Delete namespace

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  delete-namespace:
    name: Delete namespace
    runs-on: ubuntu-latest

    steps:
      - name: "Authenticate to GCP"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Delete Namespace
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          # Protect the 'main' branch from deleting its associated namespace ('project')
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "Skipping namespace deletion for 'main' branch. The 'project' namespace is protected."
          else
            NAMESPACE="$BRANCH_NAME"
            echo "Attempting to delete namespace: $NAMESPACE"
            kubectl delete namespace "$NAMESPACE" || true
            echo "Namespace deletion command executed."
          fi
